### ISSUE TITLE
Why not use the Default Cypress reporter?

### ISSUE THREAD

**Issue by Rup1** [testdrivenio/cypress-parallel#1]
Just saw your super helpful blog posts on parallelizing Cypress tests in Circle CI. May I ask why you went with the mochawesome reporter instead of using the default cypress reporter that has all the helpful bells and whistles? (like time-travel through the test, screenshots, videos, etc?)

Sorry I know this is not an issue, but your blog did not have commenting.

**Comment by mjhea0** [comment]
Feel free to email me directly - michael at mherman dot org. Cheers!
